#!/usr/bin/env sh

default="\033[0m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"

SCRIPT_DIRECTORY=$(dirname "$0")
INFLUXDB_DIRECTORY=influxdb
SUBSCRIPT_DIRECTORY="$INFLUXDB_DIRECTORY"/subScripts
PROPERTY_FILE="$SCRIPT_DIRECTORY"/script.properties

function getProperty {
   PROP_KEY=$1
   PROP_VALUE=`cat $PROPERTY_FILE | grep "$PROP_KEY" | cut -d'=' -f2`
   
   echo "${PROP_VALUE/blob/raw}"
}

echo "## Reading property from $PROPERTY_FILE"
REPOSITORY_URL=$(getProperty "repo.url")
BRANCH=$(getProperty "repo.branch")

mkdir "$SCRIPT_DIRECTORY"
curl "$REPOSITORY_URL"/"$BRANCH"/"$SUBSCRIPT_DIRECTORY"/install-docker > "$SCRIPT_DIRECTORY"/"$SUBSCRIPT_DIRECTORY"/install-docker
curl "$REPOSITORY_URL"/"$BRANCH"/"$SUBSCRIPT_DIRECTORY"/create-ssh-key > "$SCRIPT_DIRECTORY"/"$SUBSCRIPT_DIRECTORY"/create-ssh-key
curl "$REPOSITORY_URL"/"$BRANCH"/"$SUBSCRIPT_DIRECTORY"/deploy-influx-stack > "$SCRIPT_DIRECTORY"/"$SUBSCRIPT_DIRECTORY"/deploy-influx-stack
chmod 700 "$SCRIPT_DIRECTORY"/"$SUBSCRIPT_DIRECTORY"/*

# 도커 설치
echo "$yellow ## Install docker $default"
printf 'Do you want to install docker (y/n)? '
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then 
    sh "$SCRIPT_DIRECTORY"/install-docker
else
    echo "$red Cancel to install docker. $default";
fi

# 스크립트 최초 실행시 유저의 도커 실행 권한을 우회하기 위한 SSH 사용
echo "$yellow ## Create ssh key pair  $default"
printf 'Do you want to create new ssh key pair (y/n)? '
read answer


if [ "$answer" != "${answer#[Yy]}" ] ;then 
    sh "$SCRIPT_DIRECTORY"/create-ssh-key
else
    echo "$red Cancel to create key pair. $default";
    echo "If the id_rsa and id_rsa.pub keys do not exist under the '/home/$USER/.ssh/' directory, the following command will not be executed.";
fi

# SSH 를 이용한 docker stack 배포
echo "$yellow ## Deploy docker stack  $default"
printf 'Do you want to deploy now (y/n)? '
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then 
    sh "$SCRIPT_DIRECTORY"/"$SUBSCRIPT_DIRECTORY"/deploy-influx-stack

else
    echo "$red Cancel to deploy docker stack $default";
    echo "If you want to deploy docker stack, execute $yellow 'docker stack deploy --compose-file [docker-compose-path] [stack-name]' $default";
fi
