#!/usr/bin/env sh

default="\033[0m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"

echo "$green ### Install Docker Engine on Ubuntu $default"

apt-get update

echo "$green ### Add Docker's official GPG key: $default"
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

echo "$green ### Add the repository to Apt sources: $default"
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

echo "$green ### Install the latest version Docker packages.  $default"
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

echo "$green ### Add $USER in group, docker  $default"
sudo groupadd docker
sudo usermod -aG docker "$USER"
