#!/usr/bin/env sh

default="\033[0m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"

# 도커 설치
echo "$yellow ## Install docker $default"
printf 'Do you want to install docker (y/n)? '
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then 
    sh $(dirname "$0")/install-docker
else
    echo "$red Cancel to install docker. $default";
fi

# 스크립트 최초 실행시 유저의 도커 실행 권한을 우회하기 위한 SSH 사용
echo "$yellow ## Create ssh key pair  $default"

printf 'Do you want to create new ssh key pair (y/n)? '
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then 
    sh $(dirname "$0")/create-ssh-key
else
    echo "$red Cancel to create key pair. $default";
    echo "If the id_rsa and id_rsa.pub keys do not exist under the '/home/$USER/.ssh/' directory, the following command will not be executed.";
fi

# SSH 를 이용한 docker stack 배포
echo "$yellow ## Deploy docker stack  $default"
printf 'Do you want to deploy now (y/n)? '
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then 
    sh $(dirname "$0")/deploy-influx-stack

else
    echo "$red Cancel to deploy docker stack $default";
    echo "If you want to deploy docker stack, execute $yellow 'docker stack deploy --compose-file [docker-compose-path] [stack-name]' $default";
fi
