#!/usr/bin/env sh

default="\033[0m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"

echo -e "$green ### Install Docker Engine on Ubuntu $default"
echo -e "$green ### Install using the apt repository $default"

apt-get update

echo -e "$green ### Add Docker's official GPG key: $default"
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

echo -e "$green ### Add the repository to Apt sources: $default"
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

echo -e "$green ### Install the latest version Docker packages.  $default"
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

echo -e "$green ### Add ubuntu in group, docker  $default"
sudo groupadd docker
sudo usermod -aG docker ubuntu

echo -e "$green ### Init Docker Swarm  $default"
sudo docker swarm init | grep "docker swarm join --token" > /home/ubuntu/docker-swarm-join-command.txt

echo -e "$green ### Create influx db stack  $default"

mkdir -p /home/ubuntu/docker/influxdb
curl https://raw.githubusercontent.com/devel0624/docker-compose/main/influxdb/compose/docker-compose.yml > /home/ubuntu/docker/influxdb/docker-compose.yml

ssh-keygen -f rsa -N ""
cp ~/.ssh/id_rsa.pub authorized_keys
chmod 600 authorized_keys

ssh ubuntu@localhost -o StrictHostKeyChecking=no docker stack deploy --compose-file /home/ubuntu/docker/influxdb/docker-compose.yml influxdb_stack
